In [2]:
import numpy as np
import matplotlib.pyplot as plt

# 1. Create a numpy array

In [3]:
a = np.array([1, 2, 3, 4, 5])
print(a)

[1 2 3 4 5]


# 2. Numpy array access element of a numpy array

In [4]:
a = np.array([1, 2, 3, 4, 5])
print(a[2])

3


# 3. Numpy array slicing

In [5]:
a = np.array([1, 2, 3, 4, 5])
print(a[1:3])

[2 3]


# 4. Numpy array length

In [6]:
a = np.array([1, 2, 3, 4, 5])
print(len(a))

5


# 5. Numpy array min, max element

In [7]:
a = np.array([1, 2, 3, 4, 5])
print(np.min(a), np.max(a))

1 5


# 6. Numpy array reshape

In [10]:
a = np.array([1, 2, 3, 4, 5, 6])
print(a.reshape(1, 6))
print(a.reshape(2, 3))

[[1 2 3 4 5 6]]
[[1 2 3]
 [4 5 6]]


# 7. Numpy array flatten

In [11]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a.flatten())

[1 2 3 4 5 6]


# 8. Numpy array transpose

In [12]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a.T)

[[1 4]
 [2 5]
 [3 6]]


# 9. Numpy array concatenate

In [13]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(np.concatenate((a, b)))

[1 2 3 4 5 6]


# 10. Numpy array split

In [14]:
a = np.array([1, 2, 3, 4, 5, 6])
print(np.split(a, 2))

[array([1, 2, 3]), array([4, 5, 6])]


# 11. Numpy array search

In [15]:
a = np.array([1, 2, 3, 4, 5, 6])
print(np.where(a == 4))

(array([3]),)


# 12. Numpy array sort

In [16]:
a = np.array([1, 3, 2, 5, 4, 6])
print(np.sort(a))

[1 2 3 4 5 6]


# 13. Numpy array filter

In [17]:
a = np.array([1, 2, 3, 4, 5, 6])
print(list(filter(lambda x: x == 4, a)))

[np.int64(4)]


# 14. Numpy array copy

In [18]:
a = np.array([1, 2, 3, 4, 5, 6])
b = a.copy()
print(b)
b[0] = 0
print(b)
print(a)

[1 2 3 4 5 6]
[0 2 3 4 5 6]
[1 2 3 4 5 6]


# 15. Numpy array clear all elements

In [19]:
a = np.array([1, 2, 3, 4, 5, 6])
print(a)
a = np.array([])
print(a)

[]


# 16. Numpy array membership

In [20]:
a = np.array([1, 2, 3, 4, 5, 6])
print(4 in a)

True


# 17. Numpy array repeat

In [21]:
a = np.array([1, 2, 3, 4, 5, 6])
print(np.repeat(a, 2))

[1 1 2 2 3 3 4 4 5 5 6 6]


# 18. Numpy create vector range and range(a, b, step)

In [23]:
a = np.arange(5)
print(a)
a = np.arange(1, 5)
print(a)
a = np.arange(1, 5, 2)
print(a)

[0 1 2 3 4]
[1 2 3 4]
[1 3]


# 19. Numpy create 3x3 matrix range(a, b, step)

In [25]:
a = np.arange(9).reshape(3, 3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


# 20. Numpy create 3x3 matrix with zeros

In [26]:
a = np.zeros((3, 3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


# 21. Numpy create 3x3 matrix with ones

In [27]:
a = np.ones((3, 3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


# 22. Numpy create 3x3 matrix with random values

In [28]:
a = np.random.random((3, 3))
print(a)

[[0.14583097 0.58075378 0.28841276]
 [0.24602763 0.15144373 0.6895659 ]
 [0.58422748 0.8340014  0.30782489]]


# 23. Numpy create 3x3 identity matrix

In [29]:
a = np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# 24. Numpy create 3x3 matrix with specific value

In [30]:
a = np.full((3, 3), 5)
print(a)

[[5 5 5]
 [5 5 5]
 [5 5 5]]


# 25. Numpy add element to numpy array

In [31]:
a = np.array([1, 2, 3, 4, 5])
a = np.append(a, 6)
print(a)

[1 2 3 4 5 6]


# 26. Numpy insert element at specific index

In [32]:
a = np.array([1, 2, 3, 4, 5])
a = np.insert(a, 2, 7)
print(a)

[1 2 7 3 4 5]


# 27. Numpy remove element from numpy array

In [33]:
a = np.array([1, 2, 3, 4, 5])
print(a)
a = np.delete(a, 2)
print(a)

[1 2 3 4 5]
[1 2 4 5]


# 28. Numpy random choice

In [34]:
a = np.array([1, 2, 3, 4, 5])
print(np.random.choice(a))

5


# 29. Numpy random permutation

In [37]:
a = np.array([1, 2, 3, 4, 5])
print(np.random.permutation(a))

[2 5 4 3 1]


# 30. Numpy random shuffle

In [40]:
a = np.array([1, 2, 3, 4, 5])
np.random.shuffle(a)
print(a)

[3 2 4 1 5]


# 31. Numpy random seed

In [41]:
np.random.seed(0)
a = np.random.random(3)
print(a)

[0.5488135  0.71518937 0.60276338]


# 32. Numpy random normal distribution

In [42]:
a = np.random.normal(0, 1, 3)
print(a)

[-2.2683282   1.33354538 -0.84272405]


# 33. Numpy random uniform distribution

In [43]:
a = np.random.uniform(1, 2, 3)
print(a)

[1.891773   1.96366276 1.38344152]


# 34. Numpy random exponential distribution

In [44]:
a = np.random.exponential(1, 3)
print(a)

[1.56889614 0.75267411 0.83943285]


# 35. Numpy random poisson distribution

In [45]:
a = np.random.poisson(1, 3)
print(a)

[1 0 0]


# 36. Numpy random geometric distribution

In [47]:
a = np.random.geometric(0.5, 3)
print(a)

[6 3 1]


# 37. Numpy random binomial distribution

In [49]:
a = np.random.binomial(10, 0.5, 3)
print(a)

[3 7 5]


# 38. Numpy random gamma distribution

In [51]:
a = np.random.gamma(1, 1, 3)
print(a)

[0.60908242 0.84033471 0.01896857]


# 39. Numpy random beta distribution

In [52]:
a = np.random.beta(1, 1, 3)
print(a)

[0.08284198 0.76120581 0.29014279]


# 40. Numpy random chisquare distribution

In [53]:
a = np.random.chisquare(2, 3)
print(a)

[0.90420411 1.68885556 1.15464862]


# 41. Numpy create 3x3x3 matrix with random values

In [54]:
a = np.random.random((3, 3, 3))
print(a)

[[[0.98837384 0.10204481 0.20887676]
  [0.16130952 0.65310833 0.2532916 ]
  [0.46631077 0.24442559 0.15896958]]

 [[0.11037514 0.65632959 0.13818295]
  [0.19658236 0.36872517 0.82099323]
  [0.09710128 0.83794491 0.09609841]]

 [[0.97645947 0.4686512  0.97676109]
  [0.60484552 0.73926358 0.03918779]
  [0.28280696 0.12019656 0.2961402 ]]]


# 42. Numpy create 3x3x3 matrix with zeros

In [55]:
a = np.zeros((3, 3, 3))
print(a)

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


# 43. Numpy 10x10 matrix with random values and find min, max, mean, median, std

In [62]:
a = np.random.random((5, 5))
print("a = ",a)
print("Natija ", np.min(a), np.max(a), np.mean(a), np.median(a), np.std(a))
b = np.random.random(25).reshape(5, 5)
print("b = ", b)
print("Natija ", np.min(b), np.max(b), np.mean(b), np.median(b), np.std(b))

a =  [[0.91950741 0.71045576 0.17700578 0.48351813 0.14031602]
 [0.35899528 0.93711704 0.92330531 0.28283685 0.33963104]
 [0.60021287 0.9631973  0.14780133 0.25691664 0.87355683]
 [0.49189223 0.89896109 0.1855179  0.53266859 0.32626963]
 [0.31654256 0.44687696 0.43307745 0.35734688 0.91497077]]
Natija  0.1403160179234194 0.96319729526038 0.5207399060182853 0.44687696394619913 0.28118873695820995
b =  [[0.73174419 0.72754699 0.28991345 0.57770942 0.77917943]
 [0.79559037 0.34453046 0.77087276 0.7358939  0.14150649]
 [0.86594547 0.44132147 0.48641045 0.44836918 0.567846  ]
 [0.62116925 0.49817957 0.86678854 0.62773476 0.40142795]
 [0.41669176 0.81083862 0.34819194 0.2114548  0.05938319]]
Natija  0.059383188005789234 0.8667885432590956 0.5426496152297681 0.5678460014775075 0.22638702814926992


# 44. Numpy creat array random  size of 30 find  mean value

In [64]:
a = np.random.random(30)
print(a)
print(a.mean())

[0.47558912 0.82002244 0.29818736 0.1509349  0.33026704 0.81388014
 0.14038396 0.22736245 0.06885196 0.70571004 0.39523324 0.31083998
 0.71862639 0.33597754 0.72777127 0.8151994  0.21766284 0.9738187
 0.16235795 0.29084091 0.17979529 0.34550566 0.48006089 0.52217587
 0.85360604 0.88944791 0.22010386 0.62289403 0.11149606 0.45896986]
0.4554524361747107


# 45. Numpy create 3x3 matrix random and find determinant int numbers

In [8]:
a = np.random.randint(1, 10, (3, 3))
print(a)
print(np.linalg.det(a))

[[2 3 5]
 [2 2 9]
 [9 5 4]]
105.00000000000006


# 46. Numpy create 3x3 matrix random and find rank

In [11]:
a = np.random.randint(1, 10, (3, 3))
print(a)
print(np.linalg.matrix_rank(a))

[[3 3 4]
 [6 5 7]
 [8 8 4]]
3


# 47. Numpy create 3x3 matrix random and find eigenvalues and eigenvectors

In [12]:
a = np.random.randint(1, 10, (3, 3))
print(a)
print(np.linalg.eig(a))

[[7 2 8]
 [7 6 5]
 [1 7 9]]
EigResult(eigenvalues=array([17.31281304+0.j        ,  2.34359348+3.91907873j,
        2.34359348-3.91907873j]), eigenvectors=array([[-0.55998049+0.j        ,  0.00640678-0.58012723j,
         0.00640678+0.58012723j],
       [-0.59932614+0.j        , -0.60138624+0.j        ,
        -0.60138624-0.j        ],
       [-0.57204023+0.j        ,  0.43081302+0.34080211j,
         0.43081302-0.34080211j]]))


# 48. Numpy create 3x3 matrix random and find inverse

In [13]:
a = np.random.randint(1, 10, (3, 3))
print(a)
print(np.linalg.inv(a))

[[7 4 2]
 [2 5 1]
 [5 7 2]]
[[ 1.          2.         -2.        ]
 [ 0.33333333  1.33333333 -1.        ]
 [-3.66666667 -9.66666667  9.        ]]


# 49. Numpy create 3x3 matrix random and find trace

In [14]:
a = np.random.randint(1, 10, (3, 3))
print(a)
print(np.trace(a))

[[8 1 7]
 [1 9 5]
 [7 9 8]]
25


# 50. Numpy create 3x3 matrix random and find diagonal

In [17]:
a = np.random.randint(1, 10, (3, 3))
print(a)
print(np.diagonal(a))

[[8 1 9]
 [4 4 3]
 [6 4 7]]
[8 4 7]


# 51. Numpy create 3x3 matrix random and find sum of diagonal

In [18]:
a = np.random.randint(1, 10, (3, 3))
print(a)
print(np.trace(a))

[[9 9 6]
 [8 1 5]
 [7 2 2]]
12


# 52. Numpy create 3x3 matrix random and find sum of rows

In [19]:
a = np.random.randint(1, 10, (3, 3))
print(a)
print(np.sum(a, axis=1))

[[1 1 8]
 [5 8 1]
 [7 2 4]]
[10 14 13]


# 53. Numpy create 3x3 matrix random and find sum of columns

In [20]:
a = np.random.randint(1, 10, (3, 3))
print(a)
print(np.sum(a, axis=0))

[[3 7 1]
 [9 2 1]
 [1 9 2]]
[13 18  4]


# 54. Numpy create 3x3 matrix random and find sum of all elements

In [21]:
a = np.random.randint(1, 10, (3, 3))
print(a)
print(np.sum(a))

[[6 7 9]
 [6 4 7]
 [8 2 1]]
50


# 55. Numpy create 3x3 matrix random and find mean of rows

In [22]:
a = np.random.randint(1, 10, (3, 3))
print(a)
print(np.mean(a, axis=1))

[[2 8 2]
 [5 5 4]
 [7 2 9]]
[4.         4.66666667 6.        ]


# 56. Numpy create 3x3 matrix random and find mean of columns

In [23]:
a = np.random.randint(1, 10, (3, 3))
print(a)
print(np.mean(a, axis=0))

[[8 4 4]
 [4 7 9]
 [3 2 9]]
[5.         4.33333333 7.33333333]


# 57. Numpy create 3x3 matrix random and find mean of all elements

In [24]:
a = np.random.randint(1, 10, (3, 3))
print(a)
print(np.mean(a))

[[1 5 8]
 [7 7 1]
 [4 7 1]]
4.555555555555555


# 58. Numpy create 3x3 matrix random and find median of rows

In [25]:
a = np.random.randint(1, 10, (3, 3))
print(a)
print(np.median(a, axis=1))

[[4 3 5]
 [9 9 8]
 [7 5 1]]
[4. 9. 5.]


# 59. Numpy create 3x3 matrix random and find median of columns

In [26]:
a = np.random.randint(1, 10, (3, 3))
print(a)
print(np.median(a, axis=0))

[[8 3 7]
 [8 4 1]
 [7 1 9]]
[8. 3. 7.]


# 60. Numpy create 3x3 matrix random and find median of all elements

In [ ]:
a = np.random.randint(1, 10, (3, 3))
print(a)
print(np.median(a))

# 61. Numpy create 3x3 matrix random and find std of rows or columns or all elements

In [29]:
a = np.random.randint(1, 10, (3, 3))
print(a)
print(np.std(a, axis=1))
print(np.std(a, axis=0))
print(np.std(a))

[[4 8 2]
 [9 1 1]
 [7 4 7]]
[2.49443826 3.77123617 1.41421356]
[2.05480467 2.86744176 2.62466929]
2.897423291201177


# 62. Numpy create 3x3 matrix random and find var of rows or columns or all elements

In [30]:
a = np.random.randint(1, 10, (3, 3))
print(a)
print(np.var(a, axis=1))
print(np.var(a, axis=0))
print(np.var(a))

[[1 4 2]
 [9 6 6]
 [8 7 5]]
[1.55555556 2.         1.55555556]
[12.66666667  1.55555556  2.88888889]
6.222222222222223


# 63. Numpy create 3x3 matrix random and find cov of rows or columns or all elements

In [31]:
a = np.random.randint(1, 10, (3, 3))
print(a)
print(np.cov(a, rowvar=True))
print(np.cov(a, rowvar=False))
print(np.cov(a))

[[8 1 1]
 [1 5 6]
 [2 4 9]]
[[ 16.33333333 -10.5        -10.5       ]
 [-10.5          7.           8.        ]
 [-10.5          8.          13.        ]]
[[ 14.33333333  -7.83333333 -13.33333333]
 [ -7.83333333   4.33333333   6.83333333]
 [-13.33333333   6.83333333  16.33333333]]
[[ 16.33333333 -10.5        -10.5       ]
 [-10.5          7.           8.        ]
 [-10.5          8.          13.        ]]


# 64. Numpy create 3x3 matrix random secondary diagonal all elements and sum, mean, median, std, prod

In [36]:
a = np.random.randint(1, 10, (3, 3))
print(a)
print(np.fliplr(a).diagonal())
print(np.sum(np.fliplr(a).diagonal()))
print(np.mean(np.fliplr(a).diagonal()))
print(np.median(np.fliplr(a).diagonal()))
print(np.std(np.fliplr(a).diagonal()))
print(np.prod(np.fliplr(a).diagonal()))

[[5 3 7]
 [3 3 9]
 [9 9 9]]
[7 3 9]
19
6.333333333333333
7.0
2.494438257849294
189


# 65. Numpy create two matrix random and find dot product

In [37]:
a = np.random.randint(1, 10, (3, 3))
b = np.random.randint(1, 10, (3, 3))
print(a)
print(b)
print(np.dot(a, b))

[[9 5 4]
 [1 2 2]
 [8 2 4]]
[[8 9 4]
 [9 3 1]
 [2 9 5]]
[[125 132  61]
 [ 30  33  16]
 [ 90 114  54]]


# 66. Numpy create two matrix random and find cross product

In [38]:
a = np.random.randint(1, 10, (3, 3))
b = np.random.randint(1, 10, (3, 3))
print(a)
print(b)
print(np.cross(a, b))

[[7 8 5]
 [5 5 5]
 [4 3 6]]
[[4 4 9]
 [8 1 1]
 [7 9 1]]
[[ 52 -43  -4]
 [  0  35 -35]
 [-51  38  15]]


# 67. Numpy create two matrix random and find inner product

In [39]:
a = np.random.randint(1, 10, (3, 3))
b = np.random.randint(1, 10, (3, 3))
print(a)
print(b)
print(np.inner(a, b))

[[7 3 4]
 [3 6 7]
 [7 2 6]]
[[7 4 3]
 [1 8 5]
 [4 6 8]]
[[ 73  51  78]
 [ 66  86 104]
 [ 75  53  88]]


# 68. Numpy create two matrix random and find outer product

In [40]:
a = np.random.randint(1, 10, (3, 3))
b = np.random.randint(1, 10, (3, 3))
print(a)
print(b)
print(np.outer(a, b))

[[5 6 1]
 [6 5 5]
 [2 9 2]]
[[1 2 7]
 [9 2 7]
 [1 6 6]]
[[ 5 10 35 45 10 35  5 30 30]
 [ 6 12 42 54 12 42  6 36 36]
 [ 1  2  7  9  2  7  1  6  6]
 [ 6 12 42 54 12 42  6 36 36]
 [ 5 10 35 45 10 35  5 30 30]
 [ 5 10 35 45 10 35  5 30 30]
 [ 2  4 14 18  4 14  2 12 12]
 [ 9 18 63 81 18 63  9 54 54]
 [ 2  4 14 18  4 14  2 12 12]]


# 69. Numpy Solve the linear system ( Ax = b ) where ( A ) is a 3x3 matrix, and ( b ) is a 3x1 column vector

In [42]:
a = np.random.randint(1, 10, (3, 3))
b = np.random.randint(1, 10, (3, 1))
print(a)
print(b)
if np.linalg.det(a) != 0:
    print(np.linalg.solve(a, b))
else:
    print("Matrix is singular")

[[6 1 5]
 [5 8 8]
 [8 4 4]]
[[8]
 [7]
 [2]]
[[-0.27272727]
 [-1.10227273]
 [ 2.14772727]]


# 70. Numpy create 3x3 matrix random and find sum of upper triangle

In [3]:
a = np.random.randint(1, 10, (3, 3))
print(a)
print(np.triu(a).sum())

[[7 5 5]
 [7 1 8]
 [3 3 9]]
35


# 71. Numpy create 3x3 matrix random and find sum of lower triangle

In [4]:
a = np.random.randint(1, 10, (3, 3))
print(a)
print(np.tril(a).sum())

[[3 4 4]
 [2 2 7]
 [4 7 1]]
19
